# Import Things

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

# Read CSV

In [2]:
df = pd.read_csv("C:\\Users\\acer\\WhiteIceAnalytics\\test.csv")

In [3]:
df['True_Adj_Sv%'] = df['True_Adj_Sv%'].fillna(0)
df['GSAA'] = df['GSAA'].fillna(0)

In [4]:
df['GP'] = df['GP'].astype(np.int64)
df['GS'] = df['GS'].astype(np.int64)
df['W'] = df['W'].astype(np.int64)
df['L'] = df['L'].astype(np.int64)
df['T'] = df['T'].astype(np.int64)
df['OT'] = df['OT'].astype(np.int64)
df['GA'] = df['GA'].astype(np.int64)
df['SO'] = df['SO'].astype(np.int64)
df['G'] = df['G'].astype(np.int64)
df['A'] = df['A'].astype(np.int64)
df['P'] = df['P'].astype(np.int64)
df['PIM'] = df['PIM'].astype(np.int64)
df['True_Adj_GAA'] = df['True_Adj_GAA'].round(2)
df['TOI'] = df['TOI'].round(2)
df['Actual GP'] = df['Actual GP'].round(2)
df['Prop GP'] = df['Prop GP'].round(2)
df['True_Adj_Sv%'] = df['True_Adj_Sv%'].round(3)
df['GSAA'] = df['GSAA'].round(2)

In [28]:
df_25 = df.loc[df['25+'] == 'Y']
df_25 = df_25.drop(columns=['S/C', 'Actual GP', 'Prop GP', '25+'])
df_25 = df_25[['Player', 'Season', 'Team', 'GP', 'GS', 'True_Adj_GAA', 'True_Adj_Sv%', 'GSAA', 'W', 'L', 'T', 'OT', 'SO', 'GAA', 'Sv%', 'SA', 'Svs', 'GA', 'TOI', 'G', 'A', 'P', 'PIM']]
df_25 = df_25.rename(columns={'Player': 'Name', 'True_Adj_GAA': 'Adj. GAA', 'True_Adj_Sv%': 'Adj. Sv%'})
df_25 = df_25.reset_index(drop=True)
df_25['Season'] = df_25['Season'].astype(str)
df_25['Season1'] = df_25['Season'].map(lambda x: x[:4])
df_25['Season2'] = df_25['Season'].map(lambda x: x[4:])
for i in range(0, len(df_25)):
    df_25['Season'][i] = df_25['Season1'][i] + "-" + df_25['Season2'][i]
df_25 = df_25.drop(columns=['Season1', 'Season2'])
df_25

<ipython-input-28-714fdbc81fcb>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_25['Season'][i] = df_25['Season1'][i] + "-" + df_25['Season2'][i]

,Name,Season,Team,GP,GS,Adj. GAA,Adj. Sv%,GSAA,W,L,T,OT,SO,GAA,Sv%,SA,Svs,GA,TOI,G,A,P,PIM
0,Georges Vezina,1917-1918,MTL,21,21,2.08,0.000,0.00,12,9,0,0,1,3.93,0.000,0,0,84,1282.25,0,0,0,0
1,Clint Benedict,1917-1918,SEN,22,22,2.70,0.000,0.00,9,13,0,0,1,5.11,0.000,0,0,114,1337.25,0,0,0,0
2,Hap Holmes,1917-1918,TAN,16,16,2.50,0.000,0.00,9,7,0,0,0,4.73,0.000,0,0,76,965.00,0,0,0,0
3,Clint Benedict,1918-1919,SEN,18,18,1.89,0.000,0.00,12,6,0,0,2,2.85,0.000,0,0,53,1114.00,0,0,0,3
4,Georges Vezina,1918-1919,MTL,18,18,2.83,0.000,0.00,10,8,0,0,1,4.27,0.000,0,0,78,1096.50,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2530,Malcolm Subban,2020-2021,CHI,16,14,3.20,0.900,-3.61,6,8,0,1,2,3.20,0.900,471,424,47,881.28,0,0,0,0
2531,Devan Dubnyk,2020-2021,"SJS,COL",22,18,3.20,0.895,-7.54,6,11,0,2,1,3.20,0.895,602,539,63,1182.37,0,0,0,2
2532,David Rittich,2020-2021,"CGY,TOR",19,15,2.86,0.901,-3.34,5,8,0,2,1,2.86,0.901,463,417,46,965.77,0,0,0,0
2533,Ryan Miller,2020-2021,ANA,16,14,3.51,0.882,-11.20,4,8,0,2,0,3.51,0.882,432,381,51,870.92,0,0,0,0
2534,Scott Wedgewood,2020-2021,NJD,16,15,3.11,0.900,-3.80,3,8,0,3,2,3.11,0.900,458,412,46,888.03,0,0,0,0

# Save As HTML

In [29]:
df_25.to_html("C:\\Users\\acer\\WhiteIceAnalytics\\index.html", index = False)

# Get Top 10 Adj. GAA Rows

In [33]:
top10_adjgaa = df_25.nsmallest(10, 'Adj. GAA')
top10_adjgaa = top10_adjgaa[['Name', 'Season', 'Team', 'GP', 'Adj. GAA', 'GAA', 'SO']]
top10_adjgaa.to_html("C:\\Users\\acer\\WhiteIceAnalytics\\top10gaa.html", index = False)

# Get Top 10 Adj. Sv% Rows

In [35]:
top10_adjsvp = df_25.nlargest(10, 'Adj. Sv%')
top10_adjsvp = top10_adjsvp[['Name', 'Season', 'Team', 'GP', 'Adj. Sv%', 'Sv%', 'SO']]
top10_adjsvp

                 Name     Season Team  GP  Adj. Sv%    Sv%  SO
449    Jacques Plante  1970-1971  TOR  40     0.949  0.944   4
588       Glenn Resch  1975-1976  NYI  44     0.947  0.928   7
803      Denis Herron  1981-1982  MTL  27     0.947  0.911   3
580        Ken Dryden  1975-1976  MTL  62     0.946  0.927   8
763    Rick St. Croix  1980-1981  PHI  27     0.946  0.913   2
553      Rogie Vachon  1974-1975  LAK  54     0.945  0.927   6
525     Bernie Parent  1973-1974  PHI  73     0.944  0.932  12
933        Bob Froese  1985-1986  PHI  51     0.944  0.909   5
820   Roland Melanson  1982-1983  NYI  44     0.943  0.909   1
1248    Dominik Hasek  1993-1994  BUF  58     0.943  0.930   7